### PR TITLE
Add fetch folder list operation

### PR DESCRIPTION
**Pull request by asmecher**
Add a "fetch folder list" operation.

### CODE REVIEW

**Comment by asmecher** [comment]
Ping! It would be nice to have this support added :)

**Comment by bsobbe** [comment]
@asmecher  thanks for the contribution and sorry for the delay. MERGED :)

**Comment by asmecher** [comment]
Thanks, @bsobbe, and no problem!

**Comment by asmecher** [comment]
Do you have plans to put out a release with this included?

**Comment by bsobbe** [comment]
@asmecher  Yes. it will be included in the next release

**Pull request merged**
